-- Create categories table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create prompts table
create table if not exists prompts (
  id bigint generated by default as identity primary key,
  content text not null,
  category_id bigint references categories(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table categories enable row level security;
alter table prompts enable row level security;

-- Create policies (Open for all for this demo tool, user can restrict)
-- Note: In a production app with users, you would check auth.uid()
create policy "Enable all access for all users" on categories for all using (true) with check (true);
create policy "Enable all access for all users" on prompts for all using (true) with check (true);
