-- Create categories table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create prompts table
create table if not exists prompts (
  id bigint generated by default as identity primary key,
  content text not null,
  category_id bigint references categories(id) on delete cascade,
  is_pinned boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create templates table (Updated: removed name)
create table if not exists templates (
  id bigint generated by default as identity primary key,
  content text not null,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table categories enable row level security;
alter table prompts enable row level security;
alter table templates enable row level security;

-- Create policies (Open for all for this demo tool, user can restrict)
create policy "Enable all access for all users" on categories for all using (true) with check (true);
create policy "Enable all access for all users" on prompts for all using (true) with check (true);
create policy "Enable all access for all users" on templates for all using (true) with check (true);

-- Storage: Create a bucket for images if it doesn't exist
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

-- Storage Policies
create policy "Public Access" on storage.objects for select using ( bucket_id = 'images' );
create policy "Public Upload" on storage.objects for insert with check ( bucket_id = 'images' );
create policy "Public Update" on storage.objects for update with check ( bucket_id = 'images' );
create policy "Public Delete" on storage.objects for delete using ( bucket_id = 'images' );

-- Migration Helper (Run this manually if table exists with old schema)
-- alter table templates drop column if exists name;
